apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoenv
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: argoenv
spec:
  project: argoenv

  source:
    repoURL: https://github.com/TheAutomationRules/helm.git
    targetRevision: main
    path: charts/argocd-apps/0.1.0
    helm:
      valueFiles:
        - values-argoenv.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: argoenv

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

  ignoreDifferences:
    - group: "*"
      kind: "*"