apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-argo-artifacts
subjects:
  - kind: ServiceAccount
    name: argo-artifacts
    namespace: default
roleRef: # referring to your ClusterRole
  kind: ClusterRole
  name: cluster-admin-argo-artifacts
  apiGroup: rbac.authorization.k8s.io
